language: java
sudo: false

os: linux
dist: bionic
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - xvfb

install: true

script:
  - mvn clean verify
    
deploy:
  # Deploy releases on every tag push
  - provider: script
    script: bash .ci/release.sh
    skip_cleanup: true
    on:
      tags: true